### ISSUE TITLE
5.15.0 fails on F34: Something went wrong installing the "sharp" module libvips-cpp.so.42: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by arcivanov** [luminoso/fedora-copr-signal-desktop#9]
Here's the culprit in main.logs

```
{"level":30,"time":"2021-08-28T01:18:43.175Z","pid":646166,"hostname":"hostname","msg":"Initializing BrowserWindow config: {\"show\":false,\"width\":1920,\"height\":1019,\"minWidth\":680,\"minHeight\":550,\"autoHideMenuBar\":false,\"titleBarStyle\":\"default\",\"backgroundColor\":\"#3a76f0\",\"webPreferences\":{\"devTools\":false,\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"contextIsolation\":false,\"enableRemoteModule\":true,\"preload\":\"/usr/lib64/signal-desktop/resources/app.asar/preload.bundle.js\",\"nativeWindowOpen\":true,\"spellcheck\":true,\"backgroundThrottling\":false},\"icon\":\"/usr/lib64/signal-desktop/resources/app.asar/images/signal-logo-desktop-linux.png\",\"x\":0,\"y\":29}"}
{"level":30,"time":"2021-08-28T01:18:43.204Z","pid":646166,"hostname":"hostname","msg":"spellcheck: user locale: en-US"}
{"level":30,"time":"2021-08-28T01:18:43.204Z","pid":646166,"hostname":"hostname","msg":"spellcheck: available spellchecker languages:  [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2021-08-28T01:18:43.204Z","pid":646166,"hostname":"hostname","msg":"spellcheck: setting languages to:  [\"en-US\"]"}
{"level":50,"time":"2021-08-28T01:18:43.671Z","pid":646166,"hostname":"hostname","msg":"Preload error in [REDACTED]/preload.bundle.js:  \nSomething went wrong installing the \"sharp\" module\n\nlibvips-cpp.so.42: cannot open shared object file: No such file or directory\n\n- Remove the \"node_modules/sharp\" directory then run\n  \"npm install --ignore-scripts=false --verbose sharp\" and look for errors\n- Consult the installation documentation at https://sharp.pixelplumbing.com/install\n- Search for this error at https://github.com/lovell/sharp/issues\n"}
```

Here's the fragment of app.logs
```
{"level":50,"time":"2021-08-28T01:18:18.877Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'storage' of undefined\n    at file://[REDACTED]/resources/app.asar/libtextsecure/protocol_wrapper.js:8:21\n    at file://[REDACTED]/resources/app.asar/libtextsecure/protocol_wrapper.js:9:3"}
{"level":50,"time":"2021-08-28T01:18:18.878Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/key_verification_view.js:10:51\n    at file://[REDACTED]/resources/app.asar/js/views/key_verification_view.js:37:3"}
{"level":50,"time":"2021-08-28T01:18:18.879Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/recorder_view.js:12:39\n    at file://[REDACTED]/resources/app.asar/js/views/recorder_view.js:149:3"}
{"level":50,"time":"2021-08-28T01:18:18.879Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/inbox_view.js:16:61\n    at file://[REDACTED]/resources/app.asar/js/views/inbox_view.js:242:3"}
{"level":50,"time":"2021-08-28T01:18:18.880Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/install_view.js:26:38\n    at file://[REDACTED]/resources/app.asar/js/views/install_view.js:238:3"}
{"level":50,"time":"2021-08-28T01:18:18.880Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/phone-input-view.js:10:41\n    at file://[REDACTED]/resources/app.asar/js/views/phone-input-view.js:40:3"}
{"level":50,"time":"2021-08-28T01:18:18.880Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/standalone_registration_view.js:12:53\n    at file://[REDACTED]/resources/app.asar/js/views/standalone_registration_view.js:106:3"}
{"level":50,"time":"2021-08-28T01:18:18.881Z","pid":646068,"hostname":"hostname","msg":"Top-level unhandled error: TypeError: window.startApp is not a function\n    at file://[REDACTED]/resources/app.asar/background.html?name=Signal&locale=en&version=5.15.0&buildExpiration=&serverUrl=https%3A%2F%2Ftextsecure-service.whispersystems.org&storageUrl=https%3A%2F%2Fstorage.signal.org
```

**Comment by ykne** [comment]
```
$ strace -e trace=file -f signal-desktop | & grep libvips
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/lib/libvips.js", O_RDONLY|O_CLOEXEC) = 41
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/glibc-hwcaps/x86-64-v2/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/tls/x86_64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/tls/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/tls/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/tls/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/x86_64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/signal-desktop/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/glibc-hwcaps/x86-64-v2/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/tls/x86_64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/tls/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/tls/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/tls/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/x86_64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/lib64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/glibc-hwcaps/x86-64-v2/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/tls/x86_64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/tls/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/tls/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/tls/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/x86_64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/x86_64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 44762] openat(AT_FDCWD, "/usr/lib64/libvips-cpp.so.42", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

```

**Comment by ykne** [comment]
@arcivanov if you need to run new signal rpm right now, here is the list of missing libraries that I gathered from different snaps, almost all came from signal-desktop snap, and copied to signal folder:
```
/usr/lib64/signal-desktop/libbz2.so.1.0
/usr/lib64/signal-desktop/libbz2.so.1.0.4
/usr/lib64/signal-desktop/libcfitsio.so.5
/usr/lib64/signal-desktop/libcfitsio.so.5.3.43
/usr/lib64/signal-desktop/libHalf.so.12
/usr/lib64/signal-desktop/libHalf.so.12.0.0
/usr/lib64/signal-desktop/libhdf5_serial.so.100
/usr/lib64/signal-desktop/libhdf5_serial.so.100.0.1
/usr/lib64/signal-desktop/libIex-2_2.so.12
/usr/lib64/signal-desktop/libIex-2_2.so.12.0.0
/usr/lib64/signal-desktop/libIlmImf-2_2.so.22
/usr/lib64/signal-desktop/libIlmImf-2_2.so.22.0.0
/usr/lib64/signal-desktop/libIlmThread-2_2.so.12
/usr/lib64/signal-desktop/libIlmThread-2_2.so.12.0.0
/usr/lib64/signal-desktop/libjpeg.so.8
/usr/lib64/signal-desktop/libjpeg.so.8.0.2
/usr/lib64/signal-desktop/libMagickCore-6.Q16.so.3
/usr/lib64/signal-desktop/libMagickCore-6.Q16.so.3.0.0
/usr/lib64/signal-desktop/libmatio.so.4
/usr/lib64/signal-desktop/libmatio.so.4.4.0
/usr/lib64/signal-desktop/libvips-cpp.so.42
/usr/lib64/signal-desktop/libvips-cpp.so.42.6.5
/usr/lib64/signal-desktop/libvips.so.42
/usr/lib64/signal-desktop/libvips.so.42.6.5
/usr/lib64/signal-desktop/libwebp.so.6
/usr/lib64/signal-desktop/libwebp.so.6.0.2

```
Apparently something happened with the build system.

**Comment by luminoso** [comment]
I'm going to stop 5.15 rollout while I investigate this. Thank you for reporting

**Comment by luminoso** [comment]
Did a little of refactoring on the spec file (reviews are welcome!)

Should be solved by now.

Can you please try to update your package and see if it works for you?

**Comment by mahavishvarupa** [comment]
> Did a little of refactoring on the spec file (reviews are welcome!)
> 
> Should be solved by now.
> 
> Can you please try to update your package and see if it works for you?

Updated RPM  (signal-desktop-5.15.0-2.fc34.x86_64 ) does not fix the issue for me on Fedora 34.

**Comment by luminoso** [comment]
In which platform are you on?

**Comment by luminoso** [comment]
Same behavior? Did you double checked if you had some signal-desktop process hanging before trying to launch it again?

**Comment by mahavishvarupa** [comment]
Platform is  AMD Ryzen 5 4600H with Radeon Graphics (from cpuinfo) laptop.  There are no signal-desktop zombie processes.

**Comment by benblasco** [comment]
Still failing with signal-desktop-5.15.0-2.fc33.x86_64 on Fedora 33, just stuck at the loading screen.

**Comment by benblasco** [comment]
fragment of app.log too:

```
{"level":50,"time":"2021-08-30T12:25:02.591Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'storage' of undefined\n    at file://[REDACTED]/resources/app.asar/libtextsecure/protocol_wrapper.js:8:21\n    at file://[REDACTED]/resources/app.asar/libtextsecure/protocol_wrapper.js:9:3"}
{"level":50,"time":"2021-08-30T12:25:02.593Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/key_verification_view.js:10:51\n    at file://[REDACTED]/resources/app.asar/js/views/key_verification_view.js:37:3"}
{"level":50,"time":"2021-08-30T12:25:02.594Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/recorder_view.js:12:39\n    at file://[REDACTED]/resources/app.asar/js/views/recorder_view.js:149:3"}
{"level":50,"time":"2021-08-30T12:25:02.594Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/inbox_view.js:16:61\n    at file://[REDACTED]/resources/app.asar/js/views/inbox_view.js:242:3"}
{"level":50,"time":"2021-08-30T12:25:02.595Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/install_view.js:26:38\n    at file://[REDACTED]/resources/app.asar/js/views/install_view.js:238:3"}
{"level":50,"time":"2021-08-30T12:25:02.595Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/phone-input-view.js:10:41\n    at file://[REDACTED]/resources/app.asar/js/views/phone-input-view.js:40:3"}
{"level":50,"time":"2021-08-30T12:25:02.595Z","pid":38154,"hostname":"bblasco-t490s","msg":"Top-level unhandled error: TypeError: Cannot read property 'extend' of undefined\n    at file://[REDACTED]/resources/app.asar/js/views/standalone_registration_view.js:12:53\n    at file://[REDACTED]/resources/app.asar/js/views/standalone_registration_view.js:106:3"}

```
[bblasco@bblasco-t490s logs]$ rpm -qa | grep ignal
signal-desktop-5.15.0-2.fc33.x86_64
```

**Comment by luminoso** [comment]
I couldn't reproduce so I've tested in a freshly installed Fedora 34 LXQT installation.
Signal didn't start up.

Could you verify if "sudo dnf install vips" and then starting signal again solves the issue for you?

**Comment by otherwiseguy** [comment]
> Could you verify if installing vips (`sudo dnf install vips`) and then starting signal again solves the issue for you?

I can verify that it fixes the issue for me, anyway.

**Comment by mahavishvarupa** [comment]
> I couldn't reproduce so I've tested in a freshly installed Fedora 34 LXQT installation.
> Signal didn't start up.
> Solved by installing vips.
> 
> Could you verify if installing vips (`sudo dnf install vips`) and then starting signal again solves the issue for you?

Installing vips fixed it for me too.  Thanks to all for debugging.

**Comment by arcivanov** [comment]
-3 works for me on F34

**Comment by luminoso** [comment]
Too bad that this implies to disable CentOS/RHEL builds. They don't have `vips` 😞 

Updated the spec file and triggered a build. `-3` it is.
Thank you for all the reports.

**Comment by benblasco** [comment]
FYI This triggers a reasonably sizeable dependency chain.  Do we have a reason why this requirement came about in the first place?

```
[bblasco@bblasco-t490s logs]$ sudo dnf install vips
[sudo] password for bblasco: 
Fedora 33 - x86_64 - Updates                                                             3.1 kB/s | 4.2 kB     00:01    
Fedora 33 - x86_64 - Updates                                                             279 kB/s | 439 kB     00:01    
Fedora Modular 33 - x86_64 - Updates                                                     4.0 kB/s | 3.4 kB     00:00    
Dependencies resolved.
=========================================================================================================================
 Package                                    Architecture      Version                           Repository          Size
=========================================================================================================================
Installing:
 vips                                       x86_64            8.9.2-2.fc33                      updates            1.4 M
Installing dependencies:
 ImageMagick-libs                           x86_64            1:6.9.11.27-1.fc33                fedora             2.3 M
 cfitsio                                    x86_64            3.470-3.fc33                      fedora             588 k
 graphviz                                   x86_64            2.44.0-14.fc33.2                  updates            3.2 M
 gts                                        x86_64            0.7.6-38.20121130.fc33            fedora             237 k
 hdf5                                       x86_64            1.10.6-2.fc33                     fedora             2.1 M
 lasi                                       x86_64            1.1.3-4.fc33                      fedora              56 k
 libXaw                                     x86_64            1.0.13-15.fc33                    fedora             201 k
 libaec                                     x86_64            1.0.4-6.fc33                      fedora              38 k
 liblqr-1                                   x86_64            0.4.2-15.fc33                     fedora              49 k
 libwmf-lite                                x86_64            0.2.12-4.fc33                     fedora              73 k
 matio                                      x86_64            1.5.21-1.fc33                     updates            138 k
 netpbm                                     x86_64            10.95.00-1.fc33                   updates            186 k
 nifticlib                                  x86_64            2.0.0-24.fc33                     fedora             160 k
 openslide                                  x86_64            3.4.1-15.fc32                     fedora             111 k
 xorg-x11-fonts-ISO8859-1-100dpi            noarch            7.5-25.fc33                       fedora             1.0 M

Transaction Summary
=========================================================================================================================
Install  16 Packages

Total download size: 12 M
Installed size: 39 M
Is this ok [y/N]: 
```

**Comment by ykne** [comment]
@benblasco apparently signal-desktop now includes "sharp" module which uses vips library.
extra 39M is not much compare to about 330M of signal-desktop itself.

**Comment by luminoso** [comment]
@benblasco no idea why they added it. I guess that to remove that dependency I would need to start patching Signal Desktop internals to remove functionality and therefore their dependencies

**Comment by benblasco** [comment]
> @benblasco no idea why they added it. I guess that to remove that dependency I would need to start patching Signal Desktop internals to remove functionality and therefore their dependencies

Thanks for explaining, and thanks for the great work you do in building this RPM for people to use on Fedora/RHEL/CentOS etc.

**Comment by bjo81** [comment]
Installed vips and cleaned .config/Signal before. Hangs now at "optimizing application" at startup.

**Comment by bjo81** [comment]
Pleae reopen, the issue is still not fixed.
